"""Adapters project the canonical workspace into each agent's native files.

Each adapter exposes `render(canonical) -> {relative_path: file_content}`.
The CLI decides whether to write (sync) or diff (status) those files.
"""
from __future__ import annotations

import json

from .core import BANNER_MD, Canonical
from .tomlw import dumps_table


def _banner(canonical: Canonical, src: str) -> str:
    return (BANNER_MD.format(src=src) + "\n\n") if canonical.banner else ""


# --- Claude Code -----------------------------------------------------------
# Instructions: CLAUDE.md at repo root, using Claude's `@import` so it reads the
# canonical file live (true single source, zero duplication).
# MCP: .mcp.json uses the exact `{"mcpServers": {...}}` schema — a 1:1 copy.
def render_claude(canonical: Canonical) -> dict[str, str]:
    out: dict[str, str] = {}
    mcp_servers = canonical.projected_mcp_servers()
    if canonical.agents_md is not None:
        body = _banner(canonical, "AGENTS.md") + "@.agentsync/AGENTS.md\n"
        out["CLAUDE.md"] = body
    if mcp_servers:
        out[".mcp.json"] = json.dumps(
            {"mcpServers": mcp_servers}, indent=2
        ) + "\n"
    return out


# --- Codex / OpenCode / Zed / Cursor --------------------------------------
# Instructions: root AGENTS.md is the convergent standard read by all of them.
# MCP: Codex configures servers globally in ~/.codex/config.toml, so we emit a
# ready-to-merge TOML snippet as an artifact rather than writing a global file.
def render_codex(canonical: Canonical) -> dict[str, str]:
    out: dict[str, str] = {}
    mcp_servers = canonical.projected_mcp_servers()
    if canonical.agents_md is not None:
        out["AGENTS.md"] = _banner(canonical, "AGENTS.md") + canonical.agents_md
    if mcp_servers:
        blocks = []
        for name, cfg in mcp_servers.items():
            table = {k: v for k, v in cfg.items() if k != "env" and v}
            if cfg.get("env"):
                table["env"] = cfg["env"]
            blocks.append(dumps_table(f"mcp_servers.{name}", table))
        snippet = (
            "# AUTO-GENERATED by AgLink — merge into ~/.codex/config.toml\n\n"
            + "\n\n".join(blocks)
            + "\n"
        )
        out[".agentsync/generated/codex.config.toml"] = snippet
    return out


# --- GitHub Copilot --------------------------------------------------------
# Instructions: .github/copilot-instructions.md (plain markdown copy).
# MCP: .vscode/mcp.json uses a `servers` key with an explicit transport `type`.
def render_copilot(canonical: Canonical) -> dict[str, str]:
    out: dict[str, str] = {}
    mcp_servers = canonical.projected_mcp_servers()
    if canonical.agents_md is not None:
        out[".github/copilot-instructions.md"] = (
            _banner(canonical, "AGENTS.md") + canonical.agents_md
        )
    if mcp_servers:
        servers = {}
        for name, cfg in mcp_servers.items():
            entry = {"type": "stdio", "command": cfg.get("command")}
            if cfg.get("args"):
                entry["args"] = cfg["args"]
            if cfg.get("env"):
                entry["env"] = cfg["env"]
            servers[name] = entry
        out[".vscode/mcp.json"] = json.dumps({"servers": servers}, indent=2) + "\n"
    return out


ADAPTERS = {
    "claude": render_claude,
    "codex": render_codex,
    "copilot": render_copilot,
}
