"""Adapters project the canonical workspace into each agent's native files.

Each adapter exposes `render(canonical) -> {relative_path: file_content}`.
The CLI decides whether to write (sync) or diff (status) those files.

Adapters in `GLOBAL_ADAPTERS` additionally target files outside the project
(e.g. `~/.codex/config.toml`); those are merged into a marked block rather
than overwritten. See `globalcfg`.
"""
from __future__ import annotations

import json
from pathlib import Path

from .core import BANNER_MD, Canonical
from .tomlw import dumps_table

# Paths whose renderer already folds in the file's existing content, so the
# CLI may overwrite them without its usual "don't clobber a user file" guard.
MERGE_SAFE = {"opencode.json"}


def _banner(canonical: Canonical, src: str) -> str:
    return (BANNER_MD.format(src=src) + "\n\n") if canonical.banner else ""


# --- Claude Code -----------------------------------------------------------
# Instructions: CLAUDE.md at repo root, using Claude's `@import` so it reads the
# canonical file live (true single source, zero duplication).
# MCP: .mcp.json uses the exact `{"mcpServers": {...}}` schema — a 1:1 copy.
def render_claude(canonical: Canonical) -> dict[str, str]:
    out: dict[str, str] = {}
    mcp_servers = canonical.projected_mcp_servers()
    if canonical.agents_md is not None:
        body = _banner(canonical, "AGENTS.md") + "@.agentsync/AGENTS.md\n"
        out["CLAUDE.md"] = body
    if mcp_servers:
        out[".mcp.json"] = json.dumps(
            {"mcpServers": mcp_servers}, indent=2
        ) + "\n"
    return out


# --- Codex / OpenCode / Zed / Cursor --------------------------------------
# Instructions: root AGENTS.md is the convergent standard read by all of them.
# MCP: Codex configures servers globally in ~/.codex/config.toml, so we emit a
# ready-to-merge TOML snippet as an artifact rather than writing a global file.
def render_codex(canonical: Canonical) -> dict[str, str]:
    out: dict[str, str] = {}
    mcp_servers = canonical.projected_mcp_servers()
    if canonical.agents_md is not None:
        out["AGENTS.md"] = _banner(canonical, "AGENTS.md") + canonical.agents_md
    if mcp_servers:
        blocks = []
        for name, cfg in mcp_servers.items():
            table = {k: v for k, v in cfg.items() if k != "env" and v}
            if cfg.get("env"):
                table["env"] = cfg["env"]
            blocks.append(dumps_table(f"mcp_servers.{name}", table))
        snippet = (
            "# AUTO-GENERATED by AgLink — merge into ~/.codex/config.toml\n\n"
            + "\n\n".join(blocks)
            + "\n"
        )
        out[".agentsync/generated/codex.config.toml"] = snippet
    return out


# --- GitHub Copilot --------------------------------------------------------
# Instructions: .github/copilot-instructions.md (plain markdown copy).
# MCP: .vscode/mcp.json uses a `servers` key with an explicit transport `type`.
def render_copilot(canonical: Canonical) -> dict[str, str]:
    out: dict[str, str] = {}
    mcp_servers = canonical.projected_mcp_servers()
    if canonical.agents_md is not None:
        out[".github/copilot-instructions.md"] = (
            _banner(canonical, "AGENTS.md") + canonical.agents_md
        )
    if mcp_servers:
        servers = {}
        for name, cfg in mcp_servers.items():
            entry = {"type": "stdio", "command": cfg.get("command")}
            if cfg.get("args"):
                entry["args"] = cfg["args"]
            if cfg.get("env"):
                entry["env"] = cfg["env"]
            servers[name] = entry
        out[".vscode/mcp.json"] = json.dumps({"servers": servers}, indent=2) + "\n"
    return out


# --- OpenCode --------------------------------------------------------------
# Instructions: root AGENTS.md (same convergent standard as Codex).
# MCP: opencode.json uses `mcp.<name>.command` as ONE argv array. That file also
# holds the user's own settings (model, theme...), so we merge our `mcp` key in
# and preserve every other key rather than overwriting the file.
def render_opencode(canonical: Canonical) -> dict[str, str]:
    out: dict[str, str] = {}
    mcp_servers = canonical.projected_mcp_servers()
    if canonical.agents_md is not None:
        out["AGENTS.md"] = _banner(canonical, "AGENTS.md") + canonical.agents_md
    if not mcp_servers:
        return out

    existing: dict = {}
    path = canonical.root / "opencode.json"
    if path.exists():
        try:
            loaded = json.loads(path.read_text(encoding="utf-8"))
            if isinstance(loaded, dict):
                existing = loaded
        except json.JSONDecodeError:
            return out  # unparseable: leave the user's file alone

    mcp = dict(existing.get("mcp") or {})
    for name, cfg in mcp_servers.items():
        entry = {
            "type": "local",
            "command": [cfg.get("command"), *cfg.get("args", [])],
            "enabled": True,
        }
        if cfg.get("env"):
            entry["environment"] = cfg["env"]
        mcp[name] = entry

    merged = dict(existing)
    merged.setdefault("$schema", "https://opencode.ai/config.json")
    merged["mcp"] = mcp
    out["opencode.json"] = json.dumps(merged, indent=2) + "\n"
    return out


# --- Global (outside-the-project) configs ----------------------------------
# Codex reads MCP servers from ~/.codex/config.toml, which also holds the
# user's own servers and trust flags -> merge into a marked block.
def global_codex(canonical: Canonical) -> list[tuple[Path, str]]:
    mcp_servers = canonical.projected_mcp_servers()
    if not mcp_servers:
        return []
    blocks = []
    for name, cfg in mcp_servers.items():
        table = {k: v for k, v in cfg.items() if k != "env" and v}
        if cfg.get("env"):
            table["env"] = cfg["env"]
        blocks.append(dumps_table(f"mcp_servers.{name}", table))
    return [(Path.home() / ".codex" / "config.toml", "\n\n".join(blocks))]


ADAPTERS = {
    "claude": render_claude,
    "codex": render_codex,
    "copilot": render_copilot,
    "opencode": render_opencode,
}

GLOBAL_ADAPTERS = {
    "codex": global_codex,
}
