"""AgLink command-line interface: init / sync / status."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from . import __version__, globalcfg, templates
from .adapters import ADAPTERS, GLOBAL_ADAPTERS, MERGE_SAFE
from .core import (
    AGENTS_FILE,
    AGENTSYNC_DIR,
    CONFIG_FILE,
    MCP_FILE,
    Canonical,
    find_root,
    load,
    load_manifest,
    save_manifest,
    sha,
)

GENERATED_MARK = "AUTO-GENERATED by AgLink"

# ANSI colors (skipped automatically when output isn't a TTY).
def _c(code: str, text: str, enable: bool) -> str:
    return f"\033[{code}m{text}\033[0m" if enable else text


def _render_all(canonical: Canonical) -> dict[str, str]:
    """Merge every enabled adapter's output into one {path: content} map."""
    files: dict[str, str] = {}
    for target in canonical.targets:
        adapter = ADAPTERS.get(target)
        if adapter is None:
            continue
        files.update(adapter(canonical))
    return files


def _render_global(canonical: Canonical) -> list[tuple[Path, str]]:
    """Blocks destined for config files outside the project."""
    blocks: list[tuple[Path, str]] = []
    if not canonical.global_configs:
        return blocks
    for target in canonical.targets:
        adapter = GLOBAL_ADAPTERS.get(target)
        if adapter is None:
            continue
        blocks.extend(adapter(canonical))
    return blocks


def cmd_init(args: argparse.Namespace) -> int:
    root = Path.cwd()
    sync_dir = root / AGENTSYNC_DIR
    sync_dir.mkdir(exist_ok=True)

    seeds = {
        AGENTS_FILE: templates.AGENTS_MD,
        MCP_FILE: templates.MCP_JSON,
        CONFIG_FILE: templates.CONFIG_TOML,
    }
    for name, content in seeds.items():
        target = sync_dir / name
        if target.exists() and not args.force:
            print(f"  skip   {AGENTSYNC_DIR}/{name} (exists)")
            continue
        target.write_text(content, encoding="utf-8")
        print(f"  write  {AGENTSYNC_DIR}/{name}")

    print(f"\nInitialized canonical workspace in {sync_dir}")
    print("Edit .agentsync/AGENTS.md and mcp.json, then run `aglink sync`.")
    return 0


def cmd_sync(args: argparse.Namespace) -> int:
    root = find_root()
    canonical = load(root)
    color = not args.no_color
    files = _render_all(canonical)
    manifest = load_manifest(root)
    new_manifest: dict[str, str] = {}
    n_written = n_skipped = n_unchanged = 0

    for rel, content in sorted(files.items()):
        path = root / rel
        new_hash = sha(content)
        new_manifest[rel] = new_hash
        existing = path.read_text(encoding="utf-8") if path.exists() else None

        # Refuse to clobber a pre-existing file we didn't generate. Files in
        # MERGE_SAFE are exempt: their renderer already folded in the existing
        # content, so writing preserves whatever the user had.
        if (
            existing is not None
            and rel not in manifest
            and rel not in MERGE_SAFE
            and GENERATED_MARK not in existing
        ):
            print(f"  {_c('33', 'skip', color)}   {rel} (user file — not overwriting)")
            n_skipped += 1
            new_manifest.pop(rel, None)
            continue

        if existing is not None and sha(existing) == new_hash:
            n_unchanged += 1
            continue

        if args.check:
            label = "would create" if existing is None else "would update"
            print(f"  {_c('36', label, color)}  {rel}")
            n_written += 1
            continue

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        action = "create" if existing is None else "update"
        print(f"  {_c('32', action, color)} {rel}")
        n_written += 1

    if not args.check:
        save_manifest(root, new_manifest)

    # Config files outside the project (e.g. ~/.codex/config.toml): merge our
    # marked block in place instead of overwriting the user's file.
    n_global = 0
    if not args.no_global:
        for path, body in _render_global(canonical):
            action = globalcfg.merge_block(path, body, dry_run=args.check)
            if action == "unchanged":
                n_unchanged += 1
                continue
            infinitive = {"created": "create", "updated": "update",
                          "appended": "append"}.get(action, action)
            label = f"would {infinitive}" if args.check else action
            print(f"  {_c('35', label, color)} {path}")
            n_global += 1

    verb = "would sync" if args.check else "synced"
    summary = (
        f"\n{verb} {n_written} file(s), {n_unchanged} unchanged, {n_skipped} skipped"
    )
    if n_global:
        summary += f", {n_global} global"
    print(f"{summary} -> targets: {', '.join(canonical.targets)}")
    return 0


# Per-agent detection: (label, marker files/dirs proving it's set up here,
# probe executables). Detection is best-effort and never fails the command.
AGENT_PROBES = {
    "claude": ("Claude Code", ["CLAUDE.md", ".mcp.json"], ["claude"]),
    "codex": ("Codex", ["AGENTS.md"], ["codex"]),
    "copilot": ("GitHub Copilot", [".github/copilot-instructions.md",
                                   ".vscode/mcp.json"], ["code"]),
    "opencode": ("OpenCode", ["AGENTS.md", "opencode.json"], ["opencode"]),
}


def cmd_doctor(args: argparse.Namespace) -> int:
    import shutil

    root = find_root()
    canonical = load(root)
    color = not args.no_color
    files = _render_all(canonical)

    print(f"AgLink doctor - root: {root}")
    print(f"targets: {', '.join(canonical.targets)}")
    print(f"gateway: {'on' if canonical.gateway else 'off'} "
          f"(name={canonical.gateway_name})")
    print(f"canonical MCP servers: {', '.join(canonical.mcp_servers) or 'none'}\n")

    problems = 0
    for target in canonical.targets:
        label, markers, probes = AGENT_PROBES.get(target, (target, [], []))
        found_bin = next((p for p in probes if shutil.which(p)), None)
        binary = f"cli: {found_bin}" if found_bin else "cli: not on PATH"
        print(f"  {label}  ({binary})")
        for marker in markers:
            path = root / marker
            if not path.exists():
                state, code = "missing ", "31"
                problems += 1
            elif marker in files and sha(
                path.read_text(encoding="utf-8")
            ) != sha(files[marker]):
                state, code = "drifted ", "33"
                problems += 1
            else:
                state, code = "ok      ", "32"
            print(f"     {_c(code, state, color)} {marker}")
        print()

    # Global configs
    for path, body in _render_global(canonical):
        action = globalcfg.merge_block(path, body, dry_run=True)
        if action == "unchanged":
            state, code = "ok      ", "32"
        else:
            state, code = f"{action:<8}", "33"
            problems += 1
        print(f"  global  {_c(code, state, color)} {path}")

    print()
    if problems:
        print(f"{problems} issue(s) found - run `aglink sync` to fix.")
        return 1
    print("All configured agents are wired up correctly.")
    return 0


def cmd_serve(args: argparse.Namespace) -> int:
    from .mcpserver import serve

    return serve(find_root())


def cmd_sessions(args: argparse.Namespace) -> int:
    from .store import SessionStore

    store = SessionStore(find_root())
    records = store.list()
    if not records:
        print("No checkpoints saved yet.")
        return 0
    for r in records:
        goal = r.get("goal") or r["summary"][:60]
        print(f"  {r['id']}  agent={r.get('agent') or '?':<12}  {goal}")
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    root = find_root()
    canonical = load(root)
    color = not args.no_color
    files = _render_all(canonical)

    print(f"AgLink status - root: {root}")
    print(f"targets: {', '.join(canonical.targets)}\n")

    drift = False
    for rel, content in sorted(files.items()):
        path = root / rel
        if not path.exists():
            print(f"  {_c('31', 'missing ', color)} {rel}")
            drift = True
        elif sha(path.read_text(encoding="utf-8")) == sha(content):
            print(f"  {_c('32', 'in-sync ', color)} {rel}")
        else:
            print(f"  {_c('33', 'drifted ', color)} {rel}")
            drift = True

    print()
    print("Run `aglink sync` to update." if drift else "Everything is in sync.")
    return 1 if drift else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="aglink",
        description="One canonical agent workspace, projected into every coding agent.",
    )
    parser.add_argument("--version", action="version", version=f"aglink {__version__}")
    parser.add_argument("--no-color", action="store_true", help="disable colored output")
    sub = parser.add_subparsers(dest="command", required=True)

    p_init = sub.add_parser("init", help="scaffold a .agentsync/ canonical workspace")
    p_init.add_argument("--force", action="store_true", help="overwrite existing files")
    p_init.set_defaults(func=cmd_init)

    p_sync = sub.add_parser("sync", help="project canonical files into each agent")
    p_sync.add_argument("--check", action="store_true", help="dry run; write nothing")
    p_sync.add_argument(
        "--no-global", action="store_true",
        help="skip config files outside the project (e.g. ~/.codex/config.toml)",
    )
    p_sync.set_defaults(func=cmd_sync)

    p_status = sub.add_parser("status", help="show which projected files are in sync")
    p_status.set_defaults(func=cmd_status)

    p_doctor = sub.add_parser(
        "doctor", help="detect installed agents and verify each is wired up"
    )
    p_doctor.set_defaults(func=cmd_doctor)

    p_serve = sub.add_parser(
        "serve", help="run the AgLink MCP server (session handoff + memory) on stdio"
    )
    p_serve.set_defaults(func=cmd_serve)

    p_sessions = sub.add_parser("sessions", help="list saved session checkpoints")
    p_sessions.set_defaults(func=cmd_sessions)

    # Best-effort: emit UTF-8 so file paths / banners never crash on Windows cp1252.
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except (AttributeError, ValueError):
            pass

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except FileNotFoundError as exc:
        print(f"error: {exc}")
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
