"""AgLink command-line interface: init / sync / status."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from . import __version__, templates
from .adapters import ADAPTERS
from .core import (
    AGENTS_FILE,
    AGENTSYNC_DIR,
    CONFIG_FILE,
    MCP_FILE,
    Canonical,
    find_root,
    load,
    load_manifest,
    save_manifest,
    sha,
)

GENERATED_MARK = "AUTO-GENERATED by AgLink"

# ANSI colors (skipped automatically when output isn't a TTY).
def _c(code: str, text: str, enable: bool) -> str:
    return f"\033[{code}m{text}\033[0m" if enable else text


def _render_all(canonical: Canonical) -> dict[str, str]:
    """Merge every enabled adapter's output into one {path: content} map."""
    files: dict[str, str] = {}
    for target in canonical.targets:
        adapter = ADAPTERS.get(target)
        if adapter is None:
            continue
        files.update(adapter(canonical))
    return files


def cmd_init(args: argparse.Namespace) -> int:
    root = Path.cwd()
    sync_dir = root / AGENTSYNC_DIR
    sync_dir.mkdir(exist_ok=True)

    seeds = {
        AGENTS_FILE: templates.AGENTS_MD,
        MCP_FILE: templates.MCP_JSON,
        CONFIG_FILE: templates.CONFIG_TOML,
    }
    for name, content in seeds.items():
        target = sync_dir / name
        if target.exists() and not args.force:
            print(f"  skip   {AGENTSYNC_DIR}/{name} (exists)")
            continue
        target.write_text(content, encoding="utf-8")
        print(f"  write  {AGENTSYNC_DIR}/{name}")

    print(f"\nInitialized canonical workspace in {sync_dir}")
    print("Edit .agentsync/AGENTS.md and mcp.json, then run `aglink sync`.")
    return 0


def cmd_sync(args: argparse.Namespace) -> int:
    root = find_root()
    canonical = load(root)
    color = not args.no_color
    files = _render_all(canonical)
    manifest = load_manifest(root)
    new_manifest: dict[str, str] = {}
    n_written = n_skipped = n_unchanged = 0

    for rel, content in sorted(files.items()):
        path = root / rel
        new_hash = sha(content)
        new_manifest[rel] = new_hash
        existing = path.read_text(encoding="utf-8") if path.exists() else None

        # Refuse to clobber a pre-existing file we didn't generate.
        if (
            existing is not None
            and rel not in manifest
            and GENERATED_MARK not in existing
        ):
            print(f"  {_c('33', 'skip', color)}   {rel} (user file — not overwriting)")
            n_skipped += 1
            new_manifest.pop(rel, None)
            continue

        if existing is not None and sha(existing) == new_hash:
            n_unchanged += 1
            continue

        if args.check:
            label = "would create" if existing is None else "would update"
            print(f"  {_c('36', label, color)}  {rel}")
            n_written += 1
            continue

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        action = "create" if existing is None else "update"
        print(f"  {_c('32', action, color)} {rel}")
        n_written += 1

    if not args.check:
        save_manifest(root, new_manifest)

    verb = "would sync" if args.check else "synced"
    print(
        f"\n{verb} {n_written} file(s), {n_unchanged} unchanged, {n_skipped} skipped "
        f"-> targets: {', '.join(canonical.targets)}"
    )
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    root = find_root()
    canonical = load(root)
    color = not args.no_color
    files = _render_all(canonical)

    print(f"AgLink status - root: {root}")
    print(f"targets: {', '.join(canonical.targets)}\n")

    drift = False
    for rel, content in sorted(files.items()):
        path = root / rel
        if not path.exists():
            print(f"  {_c('31', 'missing ', color)} {rel}")
            drift = True
        elif sha(path.read_text(encoding="utf-8")) == sha(content):
            print(f"  {_c('32', 'in-sync ', color)} {rel}")
        else:
            print(f"  {_c('33', 'drifted ', color)} {rel}")
            drift = True

    print()
    print("Run `aglink sync` to update." if drift else "Everything is in sync.")
    return 1 if drift else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="aglink",
        description="One canonical agent workspace, projected into every coding agent.",
    )
    parser.add_argument("--version", action="version", version=f"aglink {__version__}")
    parser.add_argument("--no-color", action="store_true", help="disable colored output")
    sub = parser.add_subparsers(dest="command", required=True)

    p_init = sub.add_parser("init", help="scaffold a .agentsync/ canonical workspace")
    p_init.add_argument("--force", action="store_true", help="overwrite existing files")
    p_init.set_defaults(func=cmd_init)

    p_sync = sub.add_parser("sync", help="project canonical files into each agent")
    p_sync.add_argument("--check", action="store_true", help="dry run; write nothing")
    p_sync.set_defaults(func=cmd_sync)

    p_status = sub.add_parser("status", help="show which projected files are in sync")
    p_status.set_defaults(func=cmd_status)

    # Best-effort: emit UTF-8 so file paths / banners never crash on Windows cp1252.
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except (AttributeError, ValueError):
            pass

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except FileNotFoundError as exc:
        print(f"error: {exc}")
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
