"""Canonical workspace loading, config, and project-root discovery."""
from __future__ import annotations

import hashlib
import json
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

AGENTSYNC_DIR = ".agentsync"
CONFIG_FILE = "config.toml"
AGENTS_FILE = "AGENTS.md"
MCP_FILE = "mcp.json"
MANIFEST_FILE = ".aglink-manifest.json"

DEFAULT_TARGETS = ["claude", "codex", "copilot"]
DEFAULT_GATEWAY_NAME = "aglink"

BANNER_MD = (
    "<!-- AUTO-GENERATED by AgLink — do not edit. "
    "Edit .agentsync/{src} and run `aglink sync`. -->"
)


def find_root(start: Path | None = None) -> Path:
    """Walk upward looking for a `.agentsync/` directory; fall back to cwd."""
    start = (start or Path.cwd()).resolve()
    for candidate in (start, *start.parents):
        if (candidate / AGENTSYNC_DIR).is_dir():
            return candidate
    return start


@dataclass
class Canonical:
    root: Path
    agents_md: str | None
    mcp_servers: dict
    targets: list[str] = field(default_factory=lambda: list(DEFAULT_TARGETS))
    banner: bool = True
    gateway: bool = False
    gateway_name: str = DEFAULT_GATEWAY_NAME

    @property
    def sync_dir(self) -> Path:
        return self.root / AGENTSYNC_DIR

    def projected_mcp_servers(self) -> dict:
        if not self.gateway:
            return self.mcp_servers
        cfg = self.mcp_servers.get(self.gateway_name)
        return {self.gateway_name: cfg} if cfg else {}

    def gateway_upstreams(self) -> dict:
        return {
            name: cfg
            for name, cfg in self.mcp_servers.items()
            if name != self.gateway_name
        }


def load(root: Path) -> Canonical:
    sync_dir = root / AGENTSYNC_DIR
    if not sync_dir.is_dir():
        raise FileNotFoundError(
            f"no {AGENTSYNC_DIR}/ found under {root} — run `aglink init` first"
        )

    agents_path = sync_dir / AGENTS_FILE
    agents_md = agents_path.read_text(encoding="utf-8") if agents_path.exists() else None

    mcp_path = sync_dir / MCP_FILE
    mcp_servers: dict = {}
    if mcp_path.exists():
        data = json.loads(mcp_path.read_text(encoding="utf-8"))
        mcp_servers = data.get("mcpServers", data)

    targets = list(DEFAULT_TARGETS)
    banner = True
    gateway = False
    gateway_name = DEFAULT_GATEWAY_NAME
    cfg_path = sync_dir / CONFIG_FILE
    if cfg_path.exists():
        cfg = tomllib.loads(cfg_path.read_text(encoding="utf-8"))
        section = cfg.get("aglink", {})
        targets = section.get("targets", targets)
        banner = cfg.get("options", {}).get("banner", banner)
        gateway_cfg = cfg.get("mcp", {})
        gateway = gateway_cfg.get("gateway", gateway)
        gateway_name = gateway_cfg.get("gateway_name", gateway_name)

    return Canonical(
        root=root,
        agents_md=agents_md,
        mcp_servers=mcp_servers,
        targets=targets,
        banner=banner,
        gateway=gateway,
        gateway_name=gateway_name,
    )


def sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def load_manifest(root: Path) -> dict:
    path = root / AGENTSYNC_DIR / MANIFEST_FILE
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {}


def save_manifest(root: Path, manifest: dict) -> None:
    path = root / AGENTSYNC_DIR / MANIFEST_FILE
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
